#!/bin/bash

mkdir examples/CHILDES
mkdir examples/CHILDES/optional_directories

wget -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

gunzip -c file.bin.gz > examples/CHILDES/optional_directories

python setup.py install
